### ISSUE TITLE
Phi 3 Ablation Issue

### ISSUE THREAD

**Issue by Nottlespike** [FailSpy/abliterator.py#6]
After I load the code when attempt to use "Getting refusal directions from the cached activation"

I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/abliterator.py/abliterator.py", line 247, in refusal_dirs
    refusal_dirs = {key:self.calculate_mean_dirs(key) for key in self.harmful if '.0.' not in key} # don't include layer 0, as it often becomes NaN
  File "/workspace/abliterator.py/abliterator.py", line 247, in <dictcomp>
    refusal_dirs = {key:self.calculate_mean_dirs(key) for key in self.harmful if '.0.' not in key} # don't include layer 0, as it often becomes NaN
  File "/workspace/abliterator.py/abliterator.py", line 227, in calculate_mean_dirs
    'harmless_mean': self.calculate_mean_dir(key,self.harmless),
  File "/workspace/abliterator.py/abliterator.py", line 222, in calculate_mean_dir
    return sum(d[key]) / len(d[key])
KeyError: 'blocks.1.hook_resid_pre'
```

**Comment by FailSpy** [comment]
This is ultimately a TransformerLens issue with the new models. I plan on PR'ing my fix for the latest-gen Phi-3 soon.
